<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'ФИО',
    'Add. mark' => 'Доп. оценка',
    'Note to homework' => 'Примечание к ДЗ',
    'Homework mark' => 'Оценка за ДЗ',
    'Presence' => 'Присутствие',
    'Note' => 'Примечание',
    'Enter homework...' => 'Введите домашнее задание...',
    'Give homework' => 'Назначить домашнее задание',
    'Students count:' => 'Количество учеников:',
    'Finish lesson' => 'Завершить урок',
    'Today:' => 'Сегодня:',
    'Begin lesson' => 'Начать урок',
    'Day' => 'День',
    'Time' => 'Время',
    'Group' => 'Класс',
    'Next lesson' => 'Следующий урок',
    'Previous lesson' => 'Предыдущий урок',
    'Today' => 'Сегодня',
    'Create' => 'Создать',
    'Update' => 'Изменить',
    'Lesson finished' => 'Урок закончен',
    'Homework' => 'Домашнее задание',
    'To edit lesson please go to tab' => 'Для редактирования урока перейдите на вкладку',
    'My groups' => 'Мои классы',
    'Lesson time' => 'Время урока',
    'Week schedule' => 'Расписание на неделю',
    'One lesson per week. So count of academic hours must be set following this rule.
        For example, if course must last 20 hours per quarter, for one lesson you must set 20/2 = 10 hours.
        For other day of week you must create one more lesson.' =>
        '"Один урок один раз в неделю. Соответственно, количество академ. часов нужно указывать с учетом одного урока в неделю.
        Например, если на урок выделено 20 часов в четверти по 2 урока в неделю, то на один урок при создании нужно указать 20 / 2 = 10 часов.
        На другой день недели нужно создать еще один урок."',
    'Select date of first lesson...' => 'Выберите дату первого урока...',
    'Create Lesson' => 'Создать урок',
    'Lessons' => 'Уроки',
    'Search' => 'Поиск',
    'Reset' => 'Сбросить',
    'Update {modelClass}: ' => 'Изменить {modelClass}',
    'Activation email' => '',
    'Journal' => 'Журнал',
    'Students' => 'Ученики',
    'Schedule' => 'Расписание',
    'Lessons'  => 'Уроки',
    'Subjects'  => 'Предметы',
    'My Classes' => 'Мои Классы',
    'This email has already been taken.' => '',
    'Your account has been successfully activated.' => '',
    'Your account has been successfully created. Check your email for further instructions.' => '',
    'Your activation link: {url}' => '',
    'About' => 'О нас',
    'Account Settings' => 'Настройки аккаунта',
    'Articles' => 'Статьи',
    'Attachments' => 'Приложения',
    'Backend' => 'Панель управления',
    'Body' => 'Сообщение',
    'Check your email for further instructions.' => 'Проверьте ваш e-mail.',
    'Confirm Password' => 'Подтвердите пароль',
    'Contact' => 'Контакты',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Ошибка в процессе OAuth авторизации.',
    'Female' => 'Женский',
    'Home' => 'Главная',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Если вы забыли пароль, вы можете сбросить его <a href="{link}">здесь</a>',
    'Incorrect username or password.' => 'Неправильный логин или пароль.',
    'Language' => 'Язык',
    'Log in with' => 'Войти с помощью',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Male' => 'Мужской',
    'Name' => 'Имя',
    'Need an account? Sign up.' => 'Нужен аккаунт? Зарегистрируйтесь',
    'New password was saved.' => 'Новый пароль был сохранен',
    'Page not found' => 'Страница не найдена',
    'Password' => 'Пароль',
    'Password reset for {name}' => 'Сброс пароля для {name}',
    'Profile settings' => 'Настройки профиля',
    'Remember Me' => 'Запомнить меня',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сброс пароля',
    'Settings' => 'Настройки',
    'Sign up with' => 'Создать аккаунт с помощью',
    'Signup' => 'Регистрация',
    'Sorry, we are unable to reset password for email provided.' => 'Извините, мы не можем сбросить пароль для этого e-mail.',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо. Мы свяжемся с Вами в ближайщее время',
    'There was an error sending email.' => 'Ошибка при отправке сообщения.',
    'This email address has already been taken.' => 'Этот e-mail уже занят',
    'This username has already been taken.' => 'Это имя пользователя уже занято',
    'Update' => 'Редактировать',
    'User Settings' => 'Настройки пользователя',
    'Username' => 'Имя пользователя',
    'Username or email' => 'Имя пользователя или e-mail',
    'Verification Code' => 'Проверочный код',
    'We already have a user with email {email}' => 'Пользователь с email {email} уже зарегистрирован.',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Добро пожаловать в {app-name}. E-mail с информацией о пользователе был отправлен на вашу почту.',
    'Your account has been successfully saved' => 'Ваш аккаунт был успешно сохранен',
    '{app-name} | Your login information' => '{app-name} | Информация о пользователе',
];
